{{<video https://youtu.be/vZQsrrmvmFI>}}

<a href="https://colab.research.google.com/github/guebin/STSC2026/blob/master/posts/Quiz6.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" style="text-align: left"></a>

# 1. `numpy`

아래와 같이 30명 학생의 5과목(국어, 영어, 수학, 과학, 사회) 점수가 기록된 자료를 고려하자.

In [ ]:
import numpy as np
np.random.seed(43052)
scores = np.random.randint(40, 101, size=(30, 5))
scores

`(1)` 학생별 평균점수를 길이 30인 1차원 `numpy array`로 계산하라.

> **hint:** 결과는 아래와 같다.
> ```
> array([60.4, 58.6, 65.6, 67.4, 62.2, 72. , 74.6, 71.6, 85. , 78.2, 69.2,
>        67.2, 76. , 73.6, 67.2, 67.4, 67. , 61.2, 70.6, 56.4, 58.6, 77. ,
>        71.2, 68.6, 71.6, 72. , 64.2, 65.2, 68.6, 66.8])
> ```

`(2)` 각 과목별로 최고점을 받은 학생의 인덱스(0~29 사이 정수)를 길이 5인 1차원 `numpy array`로 구하라.

> **hint:** 결과는 `array([17, 24, 21, 4, 23])` 이다.

`(3)` 평균점수가 70점 이상인 학생은 몇 명인가?

> **hint:** 정답은 `12` 이다.

`(4)` `scores`에서 60점 미만인 점수는 모두 60점으로 대체한 새로운 `numpy array` `scores2`를 만들어라. `scores`는 변경되지 않아야 한다.

> **hint:** `scores2`의 shape은 `(30, 5)` 이고 최솟값은 `60` 이다. `scores2`의 첫 3행은 아래와 같다.
> ```
> array([[60, 60, 83, 60, 75],
>        [60, 60, 61, 60, 86],
>        [60, 83, 67, 60, 74]])
> ```

`(5)` 30명 학생을 대상으로, 자신의 5과목 평균보다 높은 점수를 받은 과목의 개수를 길이 30인 `numpy array`로 구하라.

> 예시: 어떤 학생의 점수가 `[80, 90, 70, 60, 50]` 이고 평균이 `70` 이라면 평균보다 높은 과목은 `80, 90` 이므로 `2`가 저장된다.

> **hint:** 결과는 아래와 같다.
> ```
> array([2, 3, 3, 1, 2, 2, 3, 1, 3, 2, 3, 2, 3, 3, 3, 3, 2, 1, 3, 2, 3, 3,
>        3, 2, 2, 2, 2, 2, 2, 2])
> ```

`(6)` 각 과목에 대하여 `수강생평균점수`를 계산하라. 이후 모든 학생의 모든 과목 점수에서 해당 과목의 `수강생평균점수`를 뺀 결과를 `(30, 5)` 형태의 `numpy array` `centered`로 저장하라.

> **hint:** `수강생평균점수`는 `array([67.83, 64.73, 70.1, 70.27, 69.6])` 이다. `centered`의 첫 3행은 아래와 같다.
> ```
> array([[-24.83, -12.73,  12.9 , -21.27,   5.4 ],
>        [-26.83, -18.73,  -9.1 , -11.27,  16.4 ],
>        [-15.83,  18.27,  -3.1 , -18.27,   4.4 ]])
> ```

`(7)` 각 과목별로, `수강생평균점수` 이상을 받은 학생 수를 길이 5인 `numpy array`로 구하라.

> 예시: 예를 들어 국어의 `수강생평균점수` 가 `67.83` 이고, 30명 학생 중 국어 점수가 `67.83` 이상인 학생이 `15`명이라면, 결과 배열의 첫 번째 원소는 `15`가 된다. 이 계산을 5개 과목 모두에 대해 수행하여 길이 5인 배열로 반환하라.

> **hint:** 결과는 `array([15, 13, 14, 13, 15])` 이다.

`(8)` 학생 0번과 **점수 패턴**이 가장 다른 학생의 번호를 구하라. 단, 두 학생의 점수 패턴 차이는 **"5과목 점수 차이의 제곱의 평균"** (클수록 패턴이 다름) 으로 측정한다.

> 예시: 학생 0번의 점수가 `[43, 52, 83, 49, 75]` 이고 학생 1번의 점수가 `[41, 46, 61, 59, 86]` 이라고 하자. 두 학생의 과목별 점수차는 `[2, 6, 22, -10, -11]` 이므로, 제곱의 평균은 `(4 + 36 + 484 + 100 + 121) / 5 = 149.0` 이다. 학생 0번과 나머지 29명 각각에 대해 이 값을 계산하고, 가장 **큰** 값을 가지는 학생의 번호를 구하면 된다.

> **hint:** 정답은 학생 **8번** 이다. (이때 `d = 1161.8`)

# 2. 대면수업내용

아래 문항의 참/거짓을 판단하라.

**1.** 원격 컴퓨터 모델에서는 `ipython`이 실행되는 컴퓨터와 크롬(브라우저)이 실행되는 컴퓨터가 반드시 같아야 한다.\
**2.** 깃헙(GitHub) 저장소의 최신 내용을 코드스페이스(Codespace)로 가져와 반영하고 싶을 때는 `git pull` 명령을 사용한다.\
**3.** 학과서버 한 대에 `python==3.10`과 `python==3.12`를 동시에 사용하고 싶다면 "가상환경" 개념을 활용하면 된다.\
**4.** 코드스페이스(Codespace)는 실습실 컴퓨터(로컬)에서 직접 실행되는 프로그램이므로 네트워크 연결 없이도 사용할 수 있다.\
**5.** 코드스페이스에서 작업한 내용을 깃헙(GitHub) 저장소로 보내고 싶을 때는 `git add .`, `git commit -m .`, `git push` 세 명령어를 순서대로 실행하면 된다.